language: node_js
node_js:
  - 12

service:
  - docker

# Pre-testinf installs
install:
  -echo "nothing needs to be instaled"

# SCripts to be run as tests
before_script:
  - echo "no test"

script:
  - docker --version # print the version for loggin
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed belingamaximilien/udargam-api-feed:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push belingamaximilien/udargam-api-feed:latest