language: node_js
node_js:
  - "12"

service:
  - docker

# Pre-testinf installs
install:
  -echo "nothing needs to be instaled"

# SCripts to be run as tests
before_script:
  - echo "no test"

script:
  - docker --version # print the version for loggin
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproy ./udagram-reserveproxy
  - docker tag udagram-frontend belingamaximilien/udargam-frontend:latest
  - docker tag udagram-api-feed belingamaximilien/udargam-api-feed:latest
  - docker tag udagram-api-user belingamaximilien/udargam-api-user:latest
  - docker tag reverseproxy belingamaximilien/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push belingamaximilien/udargam-frontend:latest
  - docker push belingamaximilien/udargam-api-feed:latest
  - docker push belingamaximilien/udargam-api-user:latest
  - docker push belingamaximilien/reverseproxy:latest
